<?php

/**
 * @var MercadoPago\Core\Block\CustomTicket\Success $block
 */

$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();
$paymentResponse = $payment->getAdditionalInformation("paymentResponse");
$payment_method = $this->getPaymentMethod();
$link_to_order = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>';
?>

<?php if ($payment_method == 'mercadopago_customticket') : ?>

    <div id="box-mercadopago">
        <p class="thanks-message">Obrigado!</p>
        <p class="mp-details-title">
            Nº DO PEDIDO: <?php echo __($link_to_order); ?>
        </p>
        <span class="box-status-order">STATUS: Pedido APROVADO</span>
        <?php if ($payment_method == 'mercadopago_customticket') { ?>
            <p>
                <?php echo __('Generate the ticket and pay it wherever you want.'); ?>
            </p>
            <p>
                <?php if (isset($paymentResponse['payment_method_id']) && $paymentResponse['payment_method_id'] == 'bolbradesco') {
                    /* @escapeNotVerified */
                    echo __('Will be approved within 2 business days.');
                }?>
            </p>

            <?php if (isset($paymentResponse['transaction_details']) && $paymentResponse['transaction_details']['external_resource_url']) { ?>

                <a href="<?php echo $block->escapeUrl(urldecode($paymentResponse['transaction_details']['external_resource_url'])); ?>" target="_blank" id="btn-boleto-mercadopago">
                    <?php /* @escapeNotVerified */
                    echo __('Generate Ticket'); ?>
                </a>
            <?php } else {
                echo __('Error getting the link to the ticket. Please contact the seller.');
            } ?>
        <?php } ?>

        <div id="logo-mercadopago">
            <img src="<?php echo $block->getLogoMP(); ?>">
        </div>

        <?php echo $this->getLayout()->createBlock("Piuka\Checkout\Block\Checkout\Success\AddressInformation")->setTemplate("Piuka_Checkout::address_information.phtml")->toHtml()  ?>
    </div>

<?php endif; ?>
