<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<?php
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');
?>
<form class="form create account form-create-account"
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <h1><?= $block->escapeHtml(__('Create account')) ?></h1>
    <fieldset class="fieldset create info">
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>
        <div class="field required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email"
                       name="email"
                       id="email_address"
                       autocomplete="email"
                       value="<?= $block->escapeHtml($block->getFormData()->getEmail()) ?>"
                       title="<?= $block->escapeHtml(__('Email')) ?>"
                       class="input-text"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="input-group-register">
          <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)
              ->setObject($block->getFormData())
              ->setForceUseCustomerAttributes(true)
              ->toHtml()
          ?>
        </div>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        
        <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        
        <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        

        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>

        <?php $customerAttributes = $block->getChildBlock('customer_form_user_attributes');?>
        <?php if ($customerAttributes): ?>
            <?php $customerAttributes->setObject($block->getFormData())
                ->setEntityType('customer')
                ->setShowContainer(false);?>
            <?php $block->restoreSessionData($customerAttributes->getMetadataForm());?>
            <?= $customerAttributes->toHtml() ?>
        <?php endif;?>

        <?= $block->getChildHtml('fieldset_create_info_additional') ?>
    </fieldset>
    <?php if ($block->getShowAddressFields()): ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend><br>
            <input type="hidden" name="create_address" value="1"/>
            <div class="field company">
                <label for="company" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('company') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="company"
                           id="company"
                           value="<?= $block->escapeHtml($block->getFormData()->getCompany()) ?>"
                           title="<?= $block->escapeHtml(__('Company')) ?>"
                           class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('company') ?>"
                    />
                </div>
            </div>
            <div class="field telephone required">
                <label for="telephone" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?></span>
                </label>
                <div class="control">
                    <?php $phoneValidationClass = $addressHelper->getAttributeValidationClass('telephone'); ?>
                    <input type="text"
                           name="telephone"
                           id="telephone"
                           value="<?= $block->escapeHtml($block->getFormData()->getTelephone()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?>"
                           class="input-text <?= /* @noEscape */ $phoneValidationClass ?>"/>
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
                </label>
                <div class="control">
                    <?php $zipValidationClass = $addressHelper->getAttributeValidationClass('postcode'); ?>
                    <input type="text"
                           name="postcode"
                           value="<?= $block->escapeHtml($block->getFormData()->getPostcode()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                           id="zip"
                           class="input-text validate-zip-international <?= /* @noEscape */ $zipValidationClass ?>"
                           data-validate="{'required':true, 'validate-zip-international':true}"/>
                </div>
            </div>

            <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>

            <div class="field street-address required">
                <label for="street_1" class="label">
                <span>
                    <?= $block->escapeHtml(__('Street')) ?>
                </span>
                </label>
                <div class="control">
                    <input type="text"
                           name="street[]"
                           value="<?= $block->escapeHtml($block->getStreetLine(1)) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                           id="street_1"
                           class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                </div>
            </div>

            <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++): ?>
                <div class="field street-additional <?= (in_array($_i, [1,2,4,5])? 'required':'') ?>">
                    <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                <span><?php
                                    switch ($_i) {
                                        case 1:
                                            echo $block->escapeHtml(__('Street'));
                                            break;
                                        case 2:
                                            echo $block->escapeHtml(__('Number'));
                                            break;
                                        case 3:
                                            echo $block->escapeHtml(__('Complement'));
                                            break;
                                        case 4:
                                            echo $block->escapeHtml(__('Neighborhood'));
                                            break;
                                        default:
                                            echo $block->escapeHtml(__('Street Address: Line %1', $_i));
                                            break;
                                    }

                                    ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="street[]"
                               value="<?= $block->escapeHtml($block->getStreetLine($_i)) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                               id="street_<?= /* @noEscape */ $_i ?>"
                               class="input-text <?= (in_array($_i, [1,2,4,5])? 'required-entry':'') ?>"/>
                    </div>
                </div>
            <?php endfor; ?>

            <div class="field required">
                <label for="city" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="city"
                           value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                           class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('city') ?>"
                           id="city"/>
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span>
                </label>
                <div class="control">
                    <select id="region_id"
                            name="region_id"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                            class="validate-select region_id">
                        <option value="">
                            <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <input type="text"
                           id="region"
                           name="region"
                           value="<?= $block->escapeHtml($block->getRegion()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                           class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('region') ?>"/>
                </div>
            </div>
            <?= /* @noEscape */
            $secureRenderer->renderTag(
                'style',
                [],
                '#region_id { display:none; }
                #region { display:none; }
            ',
                true
            );
            ?>



            <div class="field country required">
                <label for="country" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
                </label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1"/>
            <input type="hidden" name="default_shipping" value="1"/>
        </fieldset>

    <?php endif; ?>
    <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
      <div class="input-group-register">
        <div class="field password required">
            <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <?php $requiredCharacterClassesNumber = $block->escapeHtmlAttr(
                    $block->getRequiredCharacterClassesNumber()
                ); ?>
                <input type="password" name="password" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= /* @noEscape */ $requiredCharacterClassesNumber ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
            </div>
        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label">
                <span><?= $block->escapeHtml(__('Confirm Password')) ?></span>
            </label>
            <div class="control">
                <input type="password"
                       name="password_confirmation"
                       title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                       id="password-confirmation"
                       class="input-text"
                       data-validate="{required:true, equalTo:'#password'}"/>
            </div>
        </div>
      </div>
    </fieldset>

    <fieldset class="fieldset additional_info">
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <?php if ($block->isNewsletterEnabled()): ?>
        <div class="field choice newsletter">
            <input type="checkbox"
                   name="is_subscribed"
                   title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                   value="1"
                   id="is_subscribed"
                <?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                   class="checkbox"/>
            <label for="is_subscribed" class="label">
                <span><?= $block->escapeHtml(__('Sign Up for Newsletter')) ?></span>
            </label>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?= $block->getChildHtml('customer.form.register.newsletter') ?>
    <?php endif ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action submit primary"
                    title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>">
                <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</form>
<?php if ($block->getShowAddressFields()): ?>
    <?php
    $displayAllRegions = $block->getConfig("general/region/display_all") ? "true" : "false";
    ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $displayAllRegions ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $directoryHelper->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $directoryHelper->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_CustomerCustomAttributes/validation": {
                "ignore": <?= (int) ($_dob->isEnabled() || $customerAttributes->hasUserDefinedAttributes()) ?>,
                "hasUserDefinedAttributes": <?= (int) $customerAttributes->hasUserDefinedAttributes() ?>,
                "isDobEnabled": <?= (int) $_dob->isEnabled() ?>,
                "disableAutoComplete": true,
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            },
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        },
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "#telephone": {
            "TheITNerd_UX/js/inputMask": {
                "mask": "(00) 0000-00000"
            }
        },
        "#zip": {
            "TheITNerd_UX/js/inputMask": {
                "mask": "00000-000"
            },
            "TheITNerd_UX/js/zipSearch": {
            }
        }
    }
</script>
