<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

$amDiscountAmount = $_item->getData("am_discount_amount");
$itemPrice = $_item->getPrice();

/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<li class="cart item">
    <div class="item-info">
        <div data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="items-options-qty"
                     data-mage-init='{"Piuka_Checkout/js/widget/update-qty": {"productId": <?= $_item->getId() ?>, "sku": "<?= $_item->getProduct()->getSku() ?>", "oldValue": <?= $block->getQty() ?>}}'>
                    <?php if ($_options = $block->getOptionList()): ?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option): ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                            <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>
                                        <?php else: ?>
                                            <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                    <?php if ($amDiscountAmount !== $itemPrice): ?>
                        <div class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                            <div class="field qty">
                                <div class="control qty" style="display: flex">
                                    <button type="button" name="button-qty-minus"
                                            data-trigger="update-qty-<?=$_item->getId() ?>"
                                            data-simbol="-"
                                            class="button button-qty-minus">-</button>
                                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                               type="number"
                                               size="4"
                                               step="any"
                                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                               class="input-text qty"
                                               data-validate="{required:true,'validate-greater-than-zero':true}"
                                               data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                               data-role="cart-item-qty"
                                                inputmode="numeric"
                                        />
                                    </label>
                                    <button type="button" name="button-qty-plus"
                                            data-trigger="update-qty-<?=$_item->getId() ?>"
                                            data-simbol="+"
                                            class="button button-qty-plus">+</button>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
                <div class="qty-unavaliable-<?=$_item->getId() ?>" style="display: none;">
                    <span class="qty-unavaliable-message">
                        A quantidade solicitada não está disponível. Retornamos com a quantidade informada anteriormente.
                    </span>
                </div>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
                <?php if ($canApplyMsrp): ?>
                    <div class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                        <span class="pricing msrp">
                            <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                            <a href="#" class="action help map"
                               id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                               data-mage-init='{"addToCart":{
                                                    "origin": "info",
                                                    "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                                    "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                                    "showAddToCart": false
                                                    }
                                                }'
                            >
                                <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                            </a>
                        </span>
                    </div>
                <?php else: ?>
                    <div class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                        <?= $block->getUnitPriceHtml($_item) ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="item-actions">
        <div colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </div>
    </div>
</li>
